spring:
  application:
    name: student
  datasource:
    url: jdbc:mysql://localhost:3306/bootcamp
    username: root
    password: Gursidak@1802
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true